# Generated by Django 5.0.4 on 2025-11-13 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('UNIT_SUBTREE', 'Đơn vị và tất cả tổ trực thuộc'), ('PLANT_SUBTREE', 'Nhà máy và toàn bộ bên dưới'), ('ALL_ORG', 'Toàn hệ thống')], db_index=True, default='UNIT_SUBTREE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_org_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_controls', to='organization.orgunit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_control', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scope'], name='hr_accessco_scope_359d26_idx')],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('workforce_type', models.CharField(choices=[('INDIRECT', 'Gián tiếp'), ('WORKER', 'Người lao động')], db_index=True, max_length=16)),
                ('card_id', models.CharField(max_length=32, unique=True)),
                ('citizen_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tax_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('bank_account', models.CharField(blank=True, max_length=34, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang làm'), ('INACTIVE', 'Tạm ngưng'), ('LEFT', 'Đã nghỉ')], db_index=True, default='ACTIVE', max_length=16)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.jobtitle')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_employees', to='organization.orgunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_employees', to='organization.orgunit')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_code'],
                'indexes': [models.Index(fields=['unit'], name='hr_employee_unit_id_f7c794_idx'), models.Index(fields=['team'], name='hr_employee_team_id_77559a_idx'), models.Index(fields=['job_title'], name='hr_employee_job_tit_f9fb3f_idx'), models.Index(fields=['workforce_type'], name='hr_employee_workfor_7e29e7_idx'), models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx'), models.Index(fields=['employee_code'], name='hr_employee_employe_2fb8eb_idx'), models.Index(fields=['card_id'], name='hr_employee_card_id_279ee3_idx'), models.Index(fields=['citizen_id'], name='hr_employee_citizen_ac271a_idx'), models.Index(fields=['tax_code'], name='hr_employee_tax_cod_532cc0_idx')],
            },
        ),
    ]
