# Generated by Django 5.0.4 on 2025-11-24 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TempAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason_code', models.CharField(choices=[('HT_SX', 'Hỗ trợ sản xuất'), ('HT_BCVP', 'Hỗ trợ công việc VP'), ('THIEU_NGUON', 'Thiếu nguồn'), ('DAO_TAO', 'Đào tạo / học việc'), ('DU_AN', 'Dự án'), ('KHAC', 'Khác')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('apply_flag', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_assignments', to='hr.employee')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orgunit')),
                ('snapshot_employee_unit_at_create', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orgunit')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organization.orgunit')),
            ],
            options={
                'verbose_name': 'Điều động tạm thời',
                'verbose_name_plural': 'Điều động tạm thời',
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['employee', 'start_date'], name='hr_tempassi_employe_f092bb_idx'), models.Index(fields=['to_unit', 'start_date'], name='hr_tempassi_to_unit_fb03b8_idx'), models.Index(fields=['status'], name='hr_tempassi_status_e0d043_idx')],
            },
        ),
    ]
