# Generated by Django 5.0.4 on 2026-04-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_tempassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skip_device_attendance',
            field=models.BooleanField(db_index=True, default=False, help_text='Đặc cách: không yêu cầu đối chiếu chấm công máy (v2).'),
        ),
    ]
