# Generated by Django 5.0.4 on 2026-04-16 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_tempassignment'),
        ('organization', '0003_orgunit_organizatio_is_atte_827a07_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDeviceAgentV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Tên agent')),
                ('hostname', models.CharField(blank=True, default='', max_length=128, verbose_name='Hostname')),
                ('ip_address', models.CharField(blank=True, default='', max_length=64, verbose_name='IP')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='Phiên bản')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('ACTIVE', 'Đang hoạt động'), ('DISABLED', 'Vô hiệu hóa')], default='PENDING', max_length=16, verbose_name='Trạng thái')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần online gần nhất')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('org_unit', models.ForeignKey(blank=True, help_text='Tham chiếu khu vực agent phụ trách (không bắt buộc).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_agents_v2', to='organization.orgunit', verbose_name='Đơn vị/Phân xưởng (tham chiếu)')),
            ],
            options={
                'verbose_name': 'Agent máy chấm công (v2)',
                'verbose_name_plural': 'Agents máy chấm công (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDeviceAPIKeyV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='API key')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiệu lực')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn lúc')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='attendance_devices_v2.attendancedeviceagentv2', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'API key của agent (v2)',
                'verbose_name_plural': 'API keys của agent (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceDeviceV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Tên thiết bị')),
                ('brand', models.CharField(choices=[('ZKTeco', 'ZKTeco'), ('Other', 'Khác')], default='ZKTeco', max_length=32, verbose_name='Hãng')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='Model')),
                ('serial_no', models.CharField(blank=True, default='', max_length=64, verbose_name='Serial')),
                ('connect_mode', models.CharField(choices=[('PULL', 'Pull'), ('PUSH', 'Push'), ('IMPORT', 'Import')], default='PULL', max_length=16, verbose_name='Chế độ kết nối')),
                ('host', models.CharField(max_length=128, verbose_name='Host/IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='Port')),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=64, verbose_name='Múi giờ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('sdk_profile', models.JSONField(blank=True, null=True, verbose_name='C��u hình SDK')),
                ('last_cursor_json', models.JSONField(blank=True, null=True, verbose_name='Cursor lần cuối')),
                ('last_pull_at', models.DateTimeField(blank=True, null=True, verbose_name='Lần pull gần nhất')),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='attendance_devices_v2.attendancedeviceagentv2', verbose_name='Agent phụ trách')),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_devices_v2', to='organization.orgunit', verbose_name='Đơn vị/Phân xưởng')),
            ],
            options={
                'verbose_name': 'Thiết bị chấm công (v2)',
                'verbose_name_plural': 'Thiết bị chấm công (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceIngestLogV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Bắt đầu')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('processed', models.PositiveIntegerField(default=0, verbose_name='Đã ghi')),
                ('duplicates', models.PositiveIntegerField(default=0, verbose_name='Trùng')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='Bị loại')),
                ('success', models.BooleanField(default=False, verbose_name='Thành công')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Lỗi')),
                ('accepted_cursor_snapshot', models.JSONField(blank=True, null=True, verbose_name='Cursor chấp nhận')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_logs', to='attendance_devices_v2.attendancedeviceagentv2', verbose_name='Agent')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_logs', to='attendance_devices_v2.attendancedevicev2', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Log ingest (v2)',
                'verbose_name_plural': 'Logs ingest (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceNormalizedPunchV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_time_utc', models.DateTimeField(verbose_name='Thời điểm chuẩn (UTC)')),
                ('method', models.CharField(choices=[('FP', 'Vân tay'), ('CARD', 'Thẻ'), ('FACE', 'Khuôn mặt'), ('OTHER', 'Khác')], default='OTHER', max_length=16, verbose_name='Phương thức')),
                ('source_count', models.PositiveIntegerField(default=1, verbose_name='Số raw đã gộp')),
                ('sources_json', models.JSONField(blank=True, null=True, verbose_name='Nguồn (JSON)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('best_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_punches_v2', to='attendance_devices_v2.attendancedevicev2', verbose_name='Thiết bị ưu tiên')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_punches_v2', to='hr.employee', verbose_name='Nhân viên')),
            ],
            options={
                'verbose_name': 'Punch chuẩn hoá (v2)',
                'verbose_name_plural': 'Punch chuẩn hoá (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendancePunchMatchV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Ngày làm việc')),
                ('target_field', models.CharField(choices=[('IN1', 'IN1'), ('OUT1', 'OUT1'), ('IN2', 'IN2'), ('OUT2', 'OUT2')], max_length=8, verbose_name='Mốc')),
                ('target_time_local', models.DateTimeField(verbose_name='Giờ mục tiêu (local)')),
                ('matched_time_local', models.DateTimeField(blank=True, null=True, verbose_name='Giờ khớp (local)')),
                ('delta_seconds', models.IntegerField(blank=True, null=True, verbose_name='Lệch (giây)')),
                ('status', models.CharField(choices=[('MATCHED', 'Khớp'), ('MISSING', 'Thiếu'), ('OUT_OF_WINDOW', 'Ngoài cửa sổ'), ('AMBIGUOUS', 'Mơ hồ (nhiều lựa chọn)'), ('ONLY_ONE_PUNCH', 'Chỉ có 1 lần chấm'), ('PUNCH_WHILE_NONWORK', 'Có chấm nhưng chế độ không đi làm'), ('SHIFT_MISMATCH_SUSPECTED', 'Nghi sai ca/đăng ký')], default='MISSING', max_length=32, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('compute_run_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Compute run id')),
                ('compute_version', models.PositiveIntegerField(default=1, verbose_name='Phiên bản')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_matches_v2', to='hr.employee', verbose_name='Nhân viên')),
                ('matched_punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_v2', to='attendance_devices_v2.attendancenormalizedpunchv2', verbose_name='Punch khớp')),
            ],
            options={
                'verbose_name': 'Audit khớp punch (v2)',
                'verbose_name_plural': 'Audit khớp punch (v2)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRawPunchV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Batch ID')),
                ('device_user_id', models.CharField(max_length=64, verbose_name='UID trên máy')),
                ('event_time_local', models.DateTimeField(verbose_name='Giờ local')),
                ('event_time_utc', models.DateTimeField(verbose_name='Giờ UTC')),
                ('method', models.CharField(choices=[('FP', 'Vân tay'), ('CARD', 'Thẻ'), ('FACE', 'Khuôn mặt'), ('OTHER', 'Khác')], default='OTHER', max_length=16, verbose_name='Phương thức')),
                ('device_event_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID sự kiện trên thiết bị')),
                ('dedup_hash', models.CharField(max_length=64, verbose_name='Hash chống trùng')),
                ('meta_json', models.JSONField(blank=True, null=True, verbose_name='Metadata (JSON)')),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nhận lúc')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_punches', to='attendance_devices_v2.attendancedeviceagentv2', verbose_name='Agent')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_punches', to='attendance_devices_v2.attendancedevicev2', verbose_name='Thiết bị')),
            ],
            options={
                'verbose_name': 'Punch raw (v2)',
                'verbose_name_plural': 'Punches raw (v2)',
            },
        ),
        migrations.AddIndex(
            model_name='attendancedeviceagentv2',
            index=models.Index(fields=['status'], name='attendance__status_e8b5cb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedeviceagentv2',
            index=models.Index(fields=['hostname'], name='attendance__hostnam_8504a3_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedeviceagentv2',
            index=models.Index(fields=['ip_address'], name='attendance__ip_addr_58d005_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedeviceagentv2',
            index=models.Index(fields=['last_seen_at'], name='attendance__last_se_d7bdf2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedeviceapikeyv2',
            index=models.Index(fields=['agent', 'is_active'], name='attendance__agent_i_d4329e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedeviceapikeyv2',
            index=models.Index(fields=['expires_at'], name='attendance__expires_fae8a9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicev2',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_0d8ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicev2',
            index=models.Index(fields=['host', 'port'], name='attendance__host_d349b8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicev2',
            index=models.Index(fields=['status'], name='attendance__status_5ce511_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicev2',
            index=models.Index(fields=['assigned_agent'], name='attendance__assigne_8b0737_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicev2',
            index=models.Index(fields=['org_unit'], name='attendance__org_uni_66611a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceingestlogv2',
            index=models.Index(fields=['device', 'started_at'], name='attendance__device__0d03a6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceingestlogv2',
            index=models.Index(fields=['agent', 'started_at'], name='attendance__agent_i_ea9d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceingestlogv2',
            index=models.Index(fields=['success'], name='attendance__success_4cc04d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancenormalizedpunchv2',
            index=models.Index(fields=['employee', 'canonical_time_utc'], name='attendance__employe_ef21d8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancenormalizedpunchv2',
            index=models.Index(fields=['canonical_time_utc'], name='attendance__canonic_a4c9b6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunchmatchv2',
            index=models.Index(fields=['work_date', 'employee'], name='attendance__work_da_1a791a_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunchmatchv2',
            index=models.Index(fields=['employee', 'work_date'], name='attendance__employe_93852b_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunchmatchv2',
            index=models.Index(fields=['status'], name='attendance__status_267b23_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunchmatchv2',
            index=models.Index(fields=['compute_run_id'], name='attendance__compute_9a94f9_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawpunchv2',
            index=models.Index(fields=['device_user_id', 'event_time_utc'], name='attendance__device__979a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawpunchv2',
            index=models.Index(fields=['device', 'event_time_utc'], name='attendance__device__1241ee_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawpunchv2',
            index=models.Index(fields=['ingested_at'], name='attendance__ingeste_9797f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerawpunchv2',
            constraint=models.UniqueConstraint(condition=models.Q(('device_event_id__isnull', True), _negated=True), fields=('device', 'device_event_id'), name='uniq_v2_device_event_id'),
        ),
        migrations.AddConstraint(
            model_name='attendancerawpunchv2',
            constraint=models.UniqueConstraint(fields=('device', 'dedup_hash'), name='uniq_v2_device_dedup_hash'),
        ),
    ]
