# Generated by Django 5.0.4 on 2026-04-17 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerawpunchv2',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chuẩn hoá lúc'),
        ),
        migrations.AddField(
            model_name='attendancerawpunchv2',
            name='normalized_punch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_raws', to='attendance_devices_v2.attendancenormalizedpunchv2', verbose_name='Punch chuẩn hoá'),
        ),
        migrations.AlterField(
            model_name='attendancedevicev2',
            name='sdk_profile',
            field=models.JSONField(blank=True, null=True, verbose_name='Cấu hình SDK'),
        ),
    ]
