# Generated by Django 5.0.4 on 2026-04-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices_v2', '0002_attendancerawpunchv2_normalized_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepunchmatchv2',
            name='status',
            field=models.CharField(choices=[('MATCHED', 'Khớp'), ('MISSING', 'Thiếu'), ('OUT_OF_WINDOW', 'Ngoài cửa sổ'), ('AMBIGUOUS', 'Mơ hồ (nhiều lựa chọn)'), ('ONLY_ONE_PUNCH', 'Chỉ có 1 lần chấm'), ('PUNCH_WHILE_NONWORK', 'Có chấm nhưng chế độ không đi làm'), ('SHIFT_MISMATCH_SUSPECTED', 'Nghi sai ca/đăng ký'), ('EXEMPT', 'Đặc cách (không yêu cầu chấm máy)')], default='MISSING', max_length=32, verbose_name='Trạng thái'),
        ),
    ]
