# Generated by Django 5.0.4 on 2026-04-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices_v2', '0003_alter_attendancepunchmatchv2_status'),
        ('hr', '0003_employee_skip_device_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDailyDeviceAuditV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True)),
                ('unit_id', models.IntegerField(db_index=True)),
                ('commit_id', models.IntegerField(db_index=True)),
                ('is_exempt', models.BooleanField(db_index=True, default=False)),
                ('expected_in1', models.BooleanField(default=False)),
                ('expected_out1', models.BooleanField(default=False)),
                ('expected_in2', models.BooleanField(default=False)),
                ('expected_out2', models.BooleanField(default=False)),
                ('expected_marks', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('missing_in1', models.BooleanField(db_index=True, default=False)),
                ('missing_out1', models.BooleanField(db_index=True, default=False)),
                ('missing_in2', models.BooleanField(db_index=True, default=False)),
                ('missing_out2', models.BooleanField(db_index=True, default=False)),
                ('matched_marks', models.PositiveSmallIntegerField(default=0)),
                ('missing_marks', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('delta_in1_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('delta_out1_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('delta_in2_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('delta_out2_minutes', models.SmallIntegerField(blank=True, null=True)),
                ('compute_run_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('compute_version', models.PositiveSmallIntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_audit_daily_v2', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Device audit daily (v2)',
                'verbose_name_plural': 'Device audit daily (v2)',
                'indexes': [models.Index(fields=['work_date', 'unit_id'], name='attendance__work_da_8b61b7_idx'), models.Index(fields=['work_date', 'unit_id', 'missing_marks'], name='attendance__work_da_aa57e5_idx'), models.Index(fields=['work_date', 'unit_id', 'is_exempt'], name='attendance__work_da_627027_idx')],
                'unique_together': {('work_date', 'unit_id', 'employee')},
            },
        ),
    ]
