# Generated by Django 5.0.4 on 2026-04-28 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancecode_default_in1_and_more'),
        ('attendance_devices_v2', '0004_attendancedailydeviceauditv2'),
        ('hr', '0003_employee_skip_device_attendance'),
        ('organization', '0003_orgunit_organizatio_is_atte_827a07_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDeviceMasterListV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(db_index=True, verbose_name='Ngày làm việc')),
                ('commit_updated_at_at_compute', models.DateTimeField(blank=True, db_index=True, help_text='Dùng để phát hiện STALE khi công chốt bị sửa sau compute.', null=True, verbose_name='Commit updated_at tại thời điểm compute')),
                ('compute_state', models.CharField(choices=[('NOT_COMPUTED', 'Chưa compute'), ('COMPUTED', 'Đã compute'), ('STALE', 'Công chốt thay đổi (STALE)')], db_index=True, default='NOT_COMPUTED', max_length=16, verbose_name='Trạng thái compute')),
                ('compute_run_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Compute run id')),
                ('compute_version', models.PositiveSmallIntegerField(default=1, verbose_name='Phiên bản compute')),
                ('computed_at', models.DateTimeField(blank=True, null=True, verbose_name='Compute lúc')),
                ('is_exempt', models.BooleanField(db_index=True, default=False, verbose_name='EXEMPT (không yêu cầu chấm máy)')),
                ('expected_in1', models.BooleanField(default=False, verbose_name='Kỳ vọng IN1')),
                ('expected_out1', models.BooleanField(default=False, verbose_name='Kỳ vọng OUT1')),
                ('expected_in2', models.BooleanField(default=False, verbose_name='Kỳ vọng IN2')),
                ('expected_out2', models.BooleanField(default=False, verbose_name='Kỳ vọng OUT2')),
                ('expected_marks', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Số mốc kỳ vọng')),
                ('target_in1_local', models.DateTimeField(blank=True, null=True, verbose_name='Target IN1 (local)')),
                ('target_out1_local', models.DateTimeField(blank=True, null=True, verbose_name='Target OUT1 (local)')),
                ('target_in2_local', models.DateTimeField(blank=True, null=True, verbose_name='Target IN2 (local)')),
                ('target_out2_local', models.DateTimeField(blank=True, null=True, verbose_name='Target OUT2 (local)')),
                ('status_in1', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Status IN1')),
                ('status_out1', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Status OUT1')),
                ('status_in2', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Status IN2')),
                ('status_out2', models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Status OUT2')),
                ('actual_in1_local', models.DateTimeField(blank=True, null=True, verbose_name='Actual IN1 (local)')),
                ('actual_out1_local', models.DateTimeField(blank=True, null=True, verbose_name='Actual OUT1 (local)')),
                ('actual_in2_local', models.DateTimeField(blank=True, null=True, verbose_name='Actual IN2 (local)')),
                ('actual_out2_local', models.DateTimeField(blank=True, null=True, verbose_name='Actual OUT2 (local)')),
                ('delta_in1_seconds', models.IntegerField(blank=True, null=True, verbose_name='Delta IN1 (giây)')),
                ('delta_out1_seconds', models.IntegerField(blank=True, null=True, verbose_name='Delta OUT1 (giây)')),
                ('delta_in2_seconds', models.IntegerField(blank=True, null=True, verbose_name='Delta IN2 (giây)')),
                ('delta_out2_seconds', models.IntegerField(blank=True, null=True, verbose_name='Delta OUT2 (giây)')),
                ('override_in1_local', models.DateTimeField(blank=True, null=True, verbose_name='Override IN1 (local)')),
                ('override_out1_local', models.DateTimeField(blank=True, null=True, verbose_name='Override OUT1 (local)')),
                ('override_in2_local', models.DateTimeField(blank=True, null=True, verbose_name='Override IN2 (local)')),
                ('override_out2_local', models.DateTimeField(blank=True, null=True, verbose_name='Override OUT2 (local)')),
                ('override_at', models.DateTimeField(blank=True, null=True, verbose_name='Sửa lúc')),
                ('override_note', models.TextField(blank=True, default='', verbose_name='Ghi chú sửa')),
                ('missing_marks', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Số mốc thiếu')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_master_rows_v2', to='attendance.attendancecommit', verbose_name='Commit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_device_master_v2', to='hr.employee', verbose_name='Nhân sự')),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sửa bởi')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_device_master_v2', to='organization.orgunit', verbose_name='Đơn vị chốt công (Commit unit)')),
            ],
            options={
                'verbose_name': 'Master list chấm công máy (v2)',
                'verbose_name_plural': 'Master list chấm công máy (v2)',
            },
        ),
        migrations.DeleteModel(
            name='AttendanceDailyDeviceAuditV2',
        ),
        migrations.AddIndex(
            model_name='attendancedevicemasterlistv2',
            index=models.Index(fields=['work_date', 'unit'], name='attendance__work_da_f8500d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicemasterlistv2',
            index=models.Index(fields=['work_date', 'unit', 'missing_marks'], name='attendance__work_da_4456af_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicemasterlistv2',
            index=models.Index(fields=['work_date', 'unit', 'compute_state'], name='attendance__work_da_66da0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancedevicemasterlistv2',
            unique_together={('work_date', 'unit', 'employee')},
        ),
    ]
