# Generated by Django 5.0.4 on 2026-04-29 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendancecode_default_in1_and_more'),
        ('attendance_devices_v2', '0005_attendancedevicemasterlistv2_and_more'),
        ('hr', '0003_employee_skip_device_attendance'),
        ('organization', '0003_orgunit_organizatio_is_atte_827a07_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceManualPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_local', models.DateTimeField(db_index=True, verbose_name='Thời gian (local)')),
                ('thoi_gian_utc', models.DateTimeField(db_index=True, verbose_name='Thời gian (UTC)')),
                ('ghi_chu', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('tao_luc', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tạo lúc')),
            ],
            options={
                'verbose_name': 'Dữ liệu chấm công thêm tay',
                'verbose_name_plural': 'Dữ liệu chấm công thêm tay',
                'ordering': ['-thoi_gian_local', 'employee_id'],
            },
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_noi_dung',
            field=models.TextField(blank=True, default='', verbose_name='Nội dung yêu cầu sửa'),
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_tao_boi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Yêu cầu bởi'),
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_tao_luc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Yêu cầu lúc'),
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_trang_thai',
            field=models.CharField(choices=[('NONE', 'Không có'), ('DA_YEU_CAU', 'Đã yêu cầu'), ('DANG_XU_LY', 'Đang xử lý'), ('DA_XU_LY', 'Đã xử lý'), ('TU_CHOI', 'Từ chối')], db_index=True, default='NONE', max_length=16, verbose_name='Trạng thái yêu cầu sửa'),
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_xu_ly_boi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Xử lý bởi'),
        ),
        migrations.AddField(
            model_name='attendancedevicemasterlistv2',
            name='yeu_cau_sua_xu_ly_luc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Xử lý lúc'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='actual_in1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ máy IN1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='actual_in2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ máy IN2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='actual_out1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ máy OUT1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='actual_out2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ máy OUT2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='commit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_master_rows_v2', to='attendance.attendancecommit', verbose_name='Công đã chốt'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='compute_run_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Mã lần compute'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='delta_in1_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lệch IN1 (giây)'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='delta_in2_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lệch IN2 (giây)'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='delta_out1_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lệch OUT1 (giây)'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='delta_out2_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lệch OUT2 (giây)'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='is_exempt',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Đặc cách (không yêu cầu chấm máy)'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='override_in1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ đã sửa IN1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='override_in2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ đã sửa IN2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='override_out1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ đã sửa OUT1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='override_out2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ đã sửa OUT2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='status_in1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Trạng thái IN1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='status_in2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Trạng thái IN2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='status_out1',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Trạng thái OUT1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='status_out2',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16, verbose_name='Trạng thái OUT2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='target_in1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ mục tiêu IN1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='target_in2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ mục tiêu IN2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='target_out1_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ mục tiêu OUT1'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='target_out2_local',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Giờ mục tiêu OUT2'),
        ),
        migrations.AlterField(
            model_name='attendancedevicemasterlistv2',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_device_master_v2', to='organization.orgunit', verbose_name='Đơn vị chốt công'),
        ),
        migrations.AddIndex(
            model_name='attendancedevicemasterlistv2',
            index=models.Index(fields=['work_date', 'unit', 'yeu_cau_sua_trang_thai'], name='attendance__work_da_36b9f2_idx'),
        ),
        migrations.AddField(
            model_name='attendancemanualpunch',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_punches', to='hr.employee', verbose_name='Nhân sự'),
        ),
        migrations.AddField(
            model_name='attendancemanualpunch',
            name='tao_boi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tạo bởi'),
        ),
        migrations.AddIndex(
            model_name='attendancemanualpunch',
            index=models.Index(fields=['employee', 'thoi_gian_utc'], name='attendance__employe_f5093e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemanualpunch',
            index=models.Index(fields=['employee', 'thoi_gian_local'], name='attendance__employe_3fd13e_idx'),
        ),
    ]
