# Generated by Django 5.0.4 on 2025-11-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ví dụ: LL, LP, PL, BB, ...', max_length=16, unique=True)),
                ('label_vi', models.CharField(help_text='Nhãn hiển thị tiếng Việt', max_length=128)),
                ('segments_am_type', models.CharField(choices=[('WORK', 'Đi làm'), ('LEAVE_PAID', 'Nghỉ phép'), ('LEAVE_SICK', 'Nghỉ ốm'), ('LEAVE_COMP', 'Nghỉ bù'), ('LEAVE_UNPAID', 'Nghỉ không lương'), ('BUSINESS_TRIP', 'Công tác'), ('MATERNITY', 'Thai sản'), ('TRAINING', 'Học'), ('CHILD_SICK', 'Con ốm'), ('NONE', 'Không áp dụng')], default='WORK', max_length=32)),
                ('segments_pm_type', models.CharField(choices=[('WORK', 'Đi làm'), ('LEAVE_PAID', 'Nghỉ phép'), ('LEAVE_SICK', 'Nghỉ ốm'), ('LEAVE_COMP', 'Nghỉ bù'), ('LEAVE_UNPAID', 'Nghỉ không lương'), ('BUSINESS_TRIP', 'Công tác'), ('MATERNITY', 'Thai sản'), ('TRAINING', 'Học'), ('CHILD_SICK', 'Con ốm'), ('NONE', 'Không áp dụng')], default='WORK', max_length=32)),
                ('requires_am_work', models.BooleanField(default=True, help_text='AM yêu cầu mốc IN1/OUT1 nếu là WORK')),
                ('requires_pm_work', models.BooleanField(default=True, help_text='PM yêu cầu mốc IN2/OUT2 nếu là WORK')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mã chế độ',
                'verbose_name_plural': 'Mã chế độ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('window_minutes', models.PositiveIntegerField(default=60)),
                ('cluster_minutes', models.PositiveIntegerField(default=2)),
                ('round_registration_to_hour', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cấu hình chấm công',
                'verbose_name_plural': 'Cấu hình chấm công',
            },
        ),
    ]
