# Generated by Django 5.0.4 on 2025-11-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancecode',
            options={'ordering': ['-priority', 'code'], 'verbose_name': 'Mã chế độ', 'verbose_name_plural': 'Mã chế độ'},
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Ưu tiên hiển thị (số lớn hiển thị trước)'),
        ),
    ]
