# Generated by Django 5.0.4 on 2025-11-28 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancecode_options_attendancecode_priority'),
        ('hr', '0002_tempassignment'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('shift_code', models.CharField(blank=True, default='', max_length=32)),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã chốt')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attend_regs', to='attendance.attendancecode')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attend_regs', to='hr.employee')),
                ('unit_accounting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attend_regs', to='organization.orgunit')),
            ],
            options={
                'verbose_name': 'Đăng ký công',
                'verbose_name_plural': 'Đăng ký công',
                'ordering': ['-work_date', 'employee_id'],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
