# Generated by Django 5.0.4 on 2025-12-03 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceregistration'),
        ('hr', '0002_tempassignment'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('LOCKED_DRAFT', 'Nháp đã khóa (đã chốt)')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_batches', to='organization.orgunit')),
            ],
            options={
                'verbose_name': 'Batch chấm công (Nháp)',
                'verbose_name_plural': 'Batch chấm công (Nháp)',
                'ordering': ['-work_date', 'unit_id'],
                'unique_together': {('unit', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('committed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_commits', to='organization.orgunit')),
            ],
            options={
                'verbose_name': 'Batch chấm công (Đã chốt)',
                'verbose_name_plural': 'Batch chấm công (Đã chốt)',
                'ordering': ['-work_date', 'unit_id'],
                'unique_together': {('unit', 'work_date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Đã gửi đề nghị'), ('APPROVED_BY_UNIT', 'Đơn vị đã duyệt'), ('APPROVED_BY_HR', 'HR đã duyệt'), ('APPLIED', 'Đã áp dụng'), ('REJECTED', 'Từ chối')], default='REQUESTED', max_length=24)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_unit_at', models.DateTimeField(blank=True, null=True)),
                ('approved_hr_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('payload_json', models.JSONField(blank=True, default=list)),
                ('approved_hr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('approved_unit_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to='organization.orgunit')),
            ],
            options={
                'verbose_name': 'Phiếu đề nghị sửa chấm công',
                'verbose_name_plural': 'Phiếu đề nghị sửa chấm công',
                'ordering': ['-requested_at', 'unit_id', '-work_date'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY', 'Ca ngày'), ('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều'), ('NIGHT', 'Ca tối')], default='DAY', max_length=16)),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('bs_direction', models.CharField(choices=[('NONE', 'Không bổ sung'), ('IN', 'Bổ sung đến'), ('OUT', 'Bổ sung đi')], default='NONE', max_length=8)),
                ('include_in_unit', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attendance.attendancebatch')),
                ('bs_peer_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.orgunit')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.attendancecode')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Dòng nháp chấm công',
                'verbose_name_plural': 'Dòng nháp chấm công',
                'ordering': ['employee_id'],
                'unique_together': {('batch', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceCommitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('DAY', 'Ca ngày'), ('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều'), ('NIGHT', 'Ca tối')], default='DAY', max_length=16)),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('bs_direction', models.CharField(choices=[('NONE', 'Không bổ sung'), ('IN', 'Bổ sung đến'), ('OUT', 'Bổ sung đi')], default='NONE', max_length=8)),
                ('include_in_unit', models.BooleanField(default=True)),
                ('bs_peer_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.orgunit')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='attendance.attendancecode')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attendance.attendancecommit')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Dòng đã chốt chấm công',
                'verbose_name_plural': 'Dòng đã chốt chấm công',
                'ordering': ['employee_id'],
                'unique_together': {('commit', 'employee')},
            },
        ),
    ]
