# Generated by Django 5.0.4 on 2025-12-04 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancecode_requires_shift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecode',
            name='requires_shift',
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='is_work',
            field=models.BooleanField(default=True, help_text="Đánh dấu mã là 'đi làm'. Nếu không đi làm, disable toàn bộ IN/OUT."),
        ),
        migrations.AlterField(
            model_name='attendancebatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='requires_am_work',
            field=models.BooleanField(default=True, help_text='AM yêu cầu mốc IN1/OUT1 nếu buổi sáng là WORK'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='requires_pm_work',
            field=models.BooleanField(default=True, help_text='PM yêu cầu mốc IN2/OUT2 nếu buổi chiều là WORK'),
        ),
        migrations.AlterField(
            model_name='attendancecommit',
            name='committed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='approved_hr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='approved_unit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AttendanceRegistration',
        ),
    ]
