# Generated by Django 5.0.4 on 2025-12-04 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendancecode_requires_shift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecode',
            name='default_in1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='default_in2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='default_out1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancecode',
            name='default_out2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancebatch',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='code',
            field=models.CharField(help_text='Ví dụ: LL, L1, L2, LP, ...', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='attendancecommit',
            name='committed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='approved_hr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='approved_unit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendancecorrectionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
