# Generated by Django 5.0.4 on 2026-06-12 02:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_code_standardization_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecode',
            name='bonus_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số công phục vụ báo cáo/tính thưởng riêng.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Công nhận thưởng'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='code',
            field=models.CharField(help_text='Ví dụ: LL, L1, L2, LP, ...', max_length=16, unique=True, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='default_in1',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ vào 1'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='default_in2',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ vào 2'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='default_out1',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ ra 1'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='default_out2',
            field=models.TimeField(blank=True, null=True, verbose_name='Giờ ra 2'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Mã nền của hệ thống; không nên xóa hoặc đổi vai trò sau khi đã dùng.', verbose_name='Mã hệ thống'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='is_work',
            field=models.BooleanField(default=True, help_text='Có đi làm/có trạng thái làm việc. Việc cần chấm máy suy ra từ mốc đăng ký.', verbose_name='Có đi làm'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='label_vi',
            field=models.CharField(help_text='Tên hiển thị tiếng Việt', max_length=128, verbose_name='Tên mã'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='meal_allowance_count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = không thanh toán; 1 = một suất; có thể mở rộng 0.5/2 nếu quy chế cần.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Số suất cơm ca'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='paid_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số công được tính hưởng lương/chế độ.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Công hưởng lương'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Số lớn hiển thị trước', verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='registered_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số giờ đăng ký theo mã; không phải giờ thực tế lấy từ máy.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Giờ đăng ký'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='requires_am_work',
            field=models.BooleanField(default=True, help_text='Yêu cầu đủ Giờ vào 1/Giờ ra 1 khi có đi làm.', verbose_name='Yêu cầu mốc 1'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='requires_pm_work',
            field=models.BooleanField(default=True, help_text='Yêu cầu đủ Giờ vào 2/Giờ ra 2 khi có đi làm.', verbose_name='Yêu cầu mốc 2'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='segments_am_type',
            field=models.CharField(choices=[('WORK', 'Đi làm'), ('LEAVE_PAID', 'Nghỉ phép'), ('LEAVE_SICK', 'Nghỉ ốm'), ('LEAVE_COMP', 'Nghỉ bù'), ('LEAVE_UNPAID', 'Nghỉ không lương'), ('BUSINESS_TRIP', 'Công tác'), ('MATERNITY', 'Thai sản'), ('TRAINING', 'Học/đào tạo'), ('CHILD_SICK', 'Con ốm'), ('NONE', 'Không áp dụng')], default='WORK', max_length=32, verbose_name='Phần 1'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='segments_pm_type',
            field=models.CharField(choices=[('WORK', 'Đi làm'), ('LEAVE_PAID', 'Nghỉ phép'), ('LEAVE_SICK', 'Nghỉ ốm'), ('LEAVE_COMP', 'Nghỉ bù'), ('LEAVE_UNPAID', 'Nghỉ không lương'), ('BUSINESS_TRIP', 'Công tác'), ('MATERNITY', 'Thai sản'), ('TRAINING', 'Học/đào tạo'), ('CHILD_SICK', 'Con ốm'), ('NONE', 'Không áp dụng')], default='WORK', max_length=32, verbose_name='Phần 2'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='system_role',
            field=models.CharField(choices=[('NORMAL_DAY', 'Làm ca ngày'), ('SHIFT_1', 'Làm ca 1'), ('SHIFT_2', 'Làm ca 2'), ('SHIFT_3', 'Làm ca 3'), ('SUPPLEMENT_OUT', 'Bổ sung đi'), ('PAID_LEAVE', 'Nghỉ phép'), ('SICK_LEAVE', 'Nghỉ ốm'), ('CHILD_SICK', 'Nghỉ con ốm'), ('COMP_LEAVE', 'Nghỉ bù'), ('BUSINESS_TRIP', 'Công tác'), ('PERSONAL_LEAVE', 'Nghỉ việc riêng'), ('TRAINING', 'Đào tạo'), ('OTHER', 'Khác')], default='OTHER', help_text='Vai trò ổn định để báo cáo/code không phụ thuộc hoàn toàn vào chữ mã.', max_length=32, verbose_name='Vai trò hệ thống'),
        ),
        migrations.AlterField(
            model_name='attendancecode',
            name='work_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Số công lao động thực tế theo mã.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Công làm'),
        ),
    ]
