# Generated by Django 5.0.4 on 2026-06-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendance_code_phase5'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancebatchitem',
            name='overtime_hours',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 giờ'), (1, '1 giờ'), (2, '2 giờ'), (3, '3 giờ'), (4, '4 giờ')], default=0),
        ),
        migrations.AddField(
            model_name='attendancecommititem',
            name='overtime_hours',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 giờ'), (1, '1 giờ'), (2, '2 giờ'), (3, '3 giờ'), (4, '4 giờ')], default=0),
        ),
    ]
