# Generated by ChatGPT on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_phase6_overtime_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancecorrectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Đã gửi đề nghị"),
                    ("APPROVED_BY_UNIT", "Đơn vị đã duyệt"),
                    ("APPROVED_BY_HR", "HR đã duyệt"),
                    ("APPLIED", "Đã áp dụng"),
                    ("REJECTED", "Từ chối"),
                    ("CANCELLED", "Đã hủy"),
                ],
                default="REQUESTED",
                max_length=24,
            ),
        ),
    ]
