# Generated by ChatGPT for attendance device v2 stale tracking

from django.db import migrations, models
from django.utils import timezone


def backfill_updated_at(apps, schema_editor):
    AttendanceCommit = apps.get_model("attendance", "AttendanceCommit")
    for commit in AttendanceCommit.objects.all().only("id", "committed_at"):
        AttendanceCommit.objects.filter(id=commit.id).update(updated_at=commit.committed_at or timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_attendancecorrectionrequest_cancelled"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecommit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attendancecommit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
