# Generated by Django 5.0.4 on 2025-12-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_key', models.CharField(help_text='Mã luồng (duy nhất)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Tên luồng phê duyệt', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Mô tả')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('PUBLISHED', 'Đã công bố'), ('ARCHIVED', 'Lưu trữ')], default='DRAFT', max_length=20)),
                ('admin_unit_id', models.IntegerField(blank=True, help_text='Đơn vị quản lý lãnh đạo (ưu tiên ở flow)', null=True)),
                ('settings_json', models.JSONField(default=dict, help_text='Cấu hình chung cho luồng')),
                ('current_version', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_flows_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Luồng phê duyệt',
                'verbose_name_plural': 'Luồng phê duyệt',
            },
        ),
        migrations.CreateModel(
            name='ApprovalFlowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(help_text='Phiên bản')),
                ('steps_json', models.JSONField(help_text='Cấu hình các bước (JSON)')),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='approvals.approvalflow')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_flow_versions_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiên bản luồng phê duyệt',
                'verbose_name_plural': 'Phiên bản luồng phê duyệt',
                'unique_together': {('flow', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(help_text='Loại đối tượng nguồn (ví dụ: attendance_correction)', max_length=100)),
                ('object_id', models.CharField(help_text='ID đối tượng nguồn', max_length=100)),
                ('title', models.CharField(help_text='Tiêu đề hiển thị', max_length=255)),
                ('unit_id', models.IntegerField(blank=True, help_text='Đơn vị đích', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã gửi'), ('IN_PROGRESS', 'Đang xử lý'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Đã từ chối'), ('CANCELLED', 'Đã hủy')], default='DRAFT', max_length=20)),
                ('metadata_json', models.JSONField(default=dict, help_text='Thông tin nguồn cho người ký (snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='approvals.approvalflow')),
                ('flow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='approvals.approvalflowversion')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu phê duyệt',
                'verbose_name_plural': 'Yêu cầu phê duyệt',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('type', models.CharField(choices=[('REQUESTER', 'Người lập'), ('PARTICIPANTS_LIST', 'Người tham gia'), ('DEPT_HEADS_FROM_EMPLOYEE_UNIT', 'Lãnh đạo đơn vị của NSTK'), ('STATIC_ROLE', 'Chức danh cố định'), ('EXPLICIT_USERS', 'Chỉ định người ký')], max_length=40)),
                ('label', models.CharField(default='', help_text='Tên hiển thị bước', max_length=255)),
                ('quorum', models.CharField(choices=[('ALL', 'Tất cả phải ký'), ('ANY', 'Một người ký là đủ'), ('GROUP_ANY_ALL', 'Theo nhóm: mỗi nhóm ký 1 người, tất cả nhóm hoàn thành')], default='ALL', max_length=20)),
                ('resolver_config', models.JSONField(default=dict, help_text='Tham số xác định người ký (JSON)')),
                ('allow_overrides', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ kích hoạt'), ('ACTIVE', 'Đang ký'), ('COMPLETED', 'Hoàn tất'), ('REJECTED', 'Bị từ chối')], default='PENDING', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='approvals.approvalrequest')),
            ],
            options={
                'verbose_name': 'Bước phê duyệt',
                'verbose_name_plural': 'Bước phê duyệt',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalSigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(blank=True, default='', help_text='Chức danh snapshot (nếu có)', max_length=100)),
                ('unit_id', models.IntegerField(blank=True, help_text='Đơn vị snapshot (nếu có)', null=True)),
                ('group_key', models.CharField(blank=True, default='', help_text='Khóa nhóm (phòng) nếu dùng GROUP_ANY_ALL', max_length=100)),
                ('is_required', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('RESOLVED', 'Suy ra tự động'), ('EXPLICIT', 'Chỉ định sẵn'), ('OVERRIDE', 'Ghi đè theo yêu cầu')], default='RESOLVED', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ ký'), ('APPROVED', 'Đã phê duyệt'), ('REJECTED', 'Đã từ chối'), ('DELEGATED', 'Đã ủy quyền')], default='PENDING', max_length=20)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_signers_delegated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_signers', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='approvals.approvalstep')),
            ],
            options={
                'verbose_name': 'Người ký',
                'verbose_name_plural': 'Người ký',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Gửi phê duyệt'), ('APPROVE', 'Phê duyệt'), ('REJECT', 'Từ chối'), ('DELEGATE', 'Ủy quyền'), ('COMMENT', 'Bình luận'), ('CANCEL', 'Hủy yêu cầu')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('meta_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='approvals.approvalrequest')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='approvals.approvalsigner')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='approvals.approvalstep')),
            ],
            options={
                'verbose_name': 'Lịch sử phê duyệt',
                'verbose_name_plural': 'Lịch sử phê duyệt',
            },
        ),
    ]
