# Generated by Django 5.0.4 on 2025-12-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalflow',
            name='admin_unit_id',
            field=models.IntegerField(blank=True, help_text='Đơn vị quản lý lãnh đạo', null=True),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='object_type',
            field=models.CharField(help_text='Loại đối tượng nguồn', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalsigner',
            name='group_key',
            field=models.CharField(blank=True, default='', help_text='Khóa nhóm', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalsigner',
            name='role_title',
            field=models.CharField(blank=True, default='', help_text='Chức danh snapshot', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalsigner',
            name='unit_id',
            field=models.IntegerField(blank=True, help_text='Đơn vị snapshot', null=True),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='resolver_config',
            field=models.JSONField(default=dict, help_text='Tham số xác định người ký'),
        ),
    ]
