# Generated by Django 5.0.4 on 2025-12-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_alter_approvalflow_admin_unit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTitleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=64)),
                ('title_code', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['role_key', 'is_active'], name='approvals_r_role_ke_a09398_idx')],
                'unique_together': {('role_key', 'title_code')},
            },
        ),
    ]
