# Generated by Django 5.0.4 on 2025-12-11 03:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_roletitlemapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='content_html',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='content_schema_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['unit_id', 'status'], name='approvals_a_unit_id_bbe111_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester_id', 'status'], name='approvals_a_request_9af349_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['object_type', 'object_id'], name='approvals_a_object__0c67e9_idx'),
        ),
    ]
