# Generated by Django 5.0.4 on 2025-11-13 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MORNING', 'Ca sáng'), ('AFTERNOON', 'Ca chiều'), ('NIGHT', 'Ca tối'), ('DAY', 'Ca ngày'), ('CUSTOM', 'Tùy chỉnh')], db_index=True, max_length=16)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('breaks', models.JSONField(blank=True, null=True)),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['type'], name='organizatio_type_ab9a24_idx'), models.Index(fields=['code'], name='organizatio_code_35979e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('PLANT', 'Nhà máy'), ('DEPARTMENT', 'Phòng'), ('DIVISION', 'Ban'), ('WORKSHOP', 'Phân xưởng'), ('TEAM', 'Tổ')], db_index=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.orgunit')),
            ],
            options={
                'ordering': ['type', 'symbol'],
                'indexes': [models.Index(fields=['type'], name='organizatio_type_2c5f23_idx'), models.Index(fields=['parent'], name='organizatio_parent__f6cca1_idx'), models.Index(fields=['code'], name='organizatio_code_433284_idx'), models.Index(fields=['symbol'], name='organizatio_symbol_bc9734_idx')],
            },
        ),
    ]
