# Generated by Django 5.0.4 on 2025-12-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_add_is_attendance_unit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orgunit',
            index=models.Index(fields=['is_attendance_unit'], name='organizatio_is_atte_827a07_idx'),
        ),
    ]
