# Generated by Django 5.0.4 on 2026-01-06 08:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_tempassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('brand', models.CharField(choices=[('ZKTeco', 'ZKTeco'), ('Other', 'Other')], default='ZKTeco', max_length=32)),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('serial_no', models.CharField(blank=True, default='', max_length=64)),
                ('connect_mode', models.CharField(choices=[('PULL', 'Pull'), ('PUSH', 'Push'), ('IMPORT', 'Import')], default='PULL', max_length=16)),
                ('host', models.CharField(max_length=128)),
                ('port', models.PositiveIntegerField(default=4370)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('sdk_profile', models.JSONField(blank=True, null=True)),
                ('last_cursor_json', models.JSONField(blank=True, null=True)),
                ('last_pull_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='attendance__is_acti_b55035_idx'), models.Index(fields=['host', 'port'], name='attendance__host_8f72be_idx'), models.Index(fields=['status'], name='attendance__status_202d29_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceEventIngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('last_cursor_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_logs', to='attendance_devices.attendancedevice')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=64)),
                ('event_time_local', models.DateTimeField()),
                ('event_time_utc', models.DateTimeField()),
                ('method', models.CharField(choices=[('FP', 'Fingerprint'), ('CARD', 'Card'), ('FACE', 'Face'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('direction', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('IN', 'In'), ('OUT', 'Out')], default='UNKNOWN', max_length=16)),
                ('device_event_id', models.CharField(blank=True, max_length=128, null=True)),
                ('dedup_hash', models.CharField(max_length=64)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('meta_json', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_events', to='attendance_devices.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_events', to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceDeviceUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maps', to='attendance_devices.attendancedevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_maps', to='hr.employee')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'device_user_id'], name='attendance__device__f781a2_idx'), models.Index(fields=['employee'], name='attendance__employe_fdd5e5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancedeviceusermap',
            constraint=models.UniqueConstraint(fields=('device', 'device_user_id', 'is_active'), name='uniq_device_user_active'),
        ),
        migrations.AddIndex(
            model_name='attendanceeventingestlog',
            index=models.Index(fields=['device', 'started_at'], name='attendance__device__982ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawevent',
            index=models.Index(fields=['device', 'event_time_utc'], name='attendance__device__f44589_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawevent',
            index=models.Index(fields=['employee', 'event_time_utc'], name='attendance__employe_86083f_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerawevent',
            index=models.Index(fields=['dedup_hash'], name='attendance__dedup_h_2baaa4_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerawevent',
            constraint=models.UniqueConstraint(condition=models.Q(('device_event_id__isnull', True), _negated=True), fields=('device', 'device_event_id'), name='uniq_device_event_id'),
        ),
        migrations.AddConstraint(
            model_name='attendancerawevent',
            constraint=models.UniqueConstraint(fields=('device', 'dedup_hash'), name='uniq_device_dedup_hash'),
        ),
    ]
