# Generated by Django 5.0.4 on 2026-01-07 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices', '0001_initial'),
        ('hr', '0002_tempassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDayFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('raw_count', models.PositiveIntegerField(default=0)),
                ('anomalies_json', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_facts', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Tổng hợp ngày',
                'verbose_name_plural': 'Tổng hợp ngày',
                'indexes': [models.Index(fields=['employee', 'work_date'], name='attendance__employe_b54183_idx'), models.Index(fields=['work_date'], name='attendance__work_da_2f9747_idx')],
                'unique_together': {('employee', 'work_date')},
            },
        ),
    ]
