# Generated by Django 5.0.4 on 2026-01-07 08:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices', '0002_attendancedayfacts'),
        ('hr', '0002_tempassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedayfacts',
            name='effective_in1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='effective_in2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='effective_out1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='effective_out2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='last_overlay_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='overlay_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='source_in1',
            field=models.CharField(blank=True, choices=[('RAW', 'Máy (RAW)'), ('IMPORT', 'Import'), ('MANUAL', 'Thủ công'), ('DEFAULT', 'Mặc định ca'), ('', '—')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='source_in2',
            field=models.CharField(blank=True, choices=[('RAW', 'Máy (RAW)'), ('IMPORT', 'Import'), ('MANUAL', 'Thủ công'), ('DEFAULT', 'Mặc định ca'), ('', '—')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='source_out1',
            field=models.CharField(blank=True, choices=[('RAW', 'Máy (RAW)'), ('IMPORT', 'Import'), ('MANUAL', 'Thủ công'), ('DEFAULT', 'Mặc định ca'), ('', '—')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='attendancedayfacts',
            name='source_out2',
            field=models.CharField(blank=True, choices=[('RAW', 'Máy (RAW)'), ('IMPORT', 'Import'), ('MANUAL', 'Thủ công'), ('DEFAULT', 'Mặc định ca'), ('', '—')], default='', max_length=16),
        ),
        migrations.CreateModel(
            name='AttendanceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=64, unique=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mode', models.CharField(choices=[('FILL_MISSING_ONLY', 'Chỉ bù mốc thiếu'), ('OVERWRITE_EXPLICIT', 'Ghi đè rõ ràng')], default='FILL_MISSING_ONLY', max_length=32)),
                ('reason_code', models.CharField(blank=True, choices=[('POWER_OUTAGE', 'Mất điện'), ('NETWORK_ISSUE', 'Sự cố mạng'), ('MACHINE_ERROR', 'Lỗi máy chấm công'), ('FORGOT_CHECK', 'Quên chấm công'), ('WRONG_CHECK', 'Chấm nhầm'), ('CARD_REISSUED', 'Đổi/cấp lại thẻ'), ('BUSINESS_TRIP', 'Công tác ngoài'), ('TRAINING_OFFSITE', 'Đào tạo ngoài'), ('OTHER', 'Khác')], default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('summary_json', models.JSONField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đợt import Excel/CSV (mốc ngày)',
                'verbose_name_plural': 'Đợt import Excel/CSV (mốc ngày)',
            },
        ),
        migrations.CreateModel(
            name='AttendanceImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('reason_code', models.CharField(blank=True, choices=[('POWER_OUTAGE', 'Mất điện'), ('NETWORK_ISSUE', 'Sự cố mạng'), ('MACHINE_ERROR', 'Lỗi máy chấm công'), ('FORGOT_CHECK', 'Quên chấm công'), ('WRONG_CHECK', 'Chấm nhầm'), ('CARD_REISSUED', 'Đổi/cấp lại thẻ'), ('BUSINESS_TRIP', 'Công tác ngoài'), ('TRAINING_OFFSITE', 'Đào tạo ngoài'), ('OTHER', 'Khác')], default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('valid', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True, default='')),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='attendance_devices.attendanceimportbatch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Dòng import Excel/CSV',
                'verbose_name_plural': 'Dòng import Excel/CSV',
            },
        ),
        migrations.CreateModel(
            name='AttendanceManualAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField()),
                ('in1', models.TimeField(blank=True, null=True)),
                ('out1', models.TimeField(blank=True, null=True)),
                ('in2', models.TimeField(blank=True, null=True)),
                ('out2', models.TimeField(blank=True, null=True)),
                ('reason_code', models.CharField(choices=[('POWER_OUTAGE', 'Mất điện'), ('NETWORK_ISSUE', 'Sự cố mạng'), ('MACHINE_ERROR', 'Lỗi máy chấm công'), ('FORGOT_CHECK', 'Quên chấm công'), ('WRONG_CHECK', 'Chấm nhầm'), ('CARD_REISSUED', 'Đổi/cấp lại thẻ'), ('BUSINESS_TRIP', 'Công tác ngoài'), ('TRAINING_OFFSITE', 'Đào tạo ngoài'), ('OTHER', 'Khác')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_manual_adjustments', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Điều chỉnh thủ công (mốc ngày)',
                'verbose_name_plural': 'Điều chỉnh thủ công (mốc ngày)',
            },
        ),
        migrations.AddIndex(
            model_name='attendanceimportbatch',
            index=models.Index(fields=['imported_at'], name='attendance__importe_37868d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceimportbatch',
            index=models.Index(fields=['mode'], name='attendance__mode_a3bf6c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceimportline',
            index=models.Index(fields=['employee', 'work_date'], name='attendance__employe_33e56f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceimportline',
            unique_together={('batch', 'employee', 'work_date')},
        ),
        migrations.AddIndex(
            model_name='attendancemanualadjustment',
            index=models.Index(fields=['employee', 'work_date'], name='attendance__employe_b66169_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancemanualadjustment',
            index=models.Index(fields=['applied_at'], name='attendance__applied_452fe7_idx'),
        ),
    ]
