# Generated by Django 5.0.4 on 2026-01-09 01:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_devices', '0003_attendancedayfacts_effective_in1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDeviceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('hostname', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Windows Agent',
                'verbose_name_plural': 'Windows Agents',
                'indexes': [models.Index(fields=['is_active'], name='attendance__is_acti_d788b8_idx'), models.Index(fields=['hostname'], name='attendance__hostnam_86c30e_idx'), models.Index(fields=['ip_address'], name='attendance__ip_addr_7ecad4_idx')],
            },
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='attendance_devices.attendancedeviceagent'),
        ),
        migrations.CreateModel(
            name='DeviceAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='attendance_devices.attendancedeviceagent')),
            ],
            options={
                'verbose_name': 'Agent API Key',
                'verbose_name_plural': 'Agent API Keys',
                'indexes': [models.Index(fields=['agent', 'is_active'], name='attendance__agent_i_29ed27_idx')],
            },
        ),
    ]
